Repository AY2324S1-CS2103T-F11-3/tp, pull requests merged in 2023-10, with the labels that each got.

#17 Update AboutUs file
  docs/AboutUs.md
  docs/team/andytoh1.md
Labels: documentation, priority.High

#20 Update personal info in AboutUs.md
  docs/AboutUs.md
  docs/images/peasantbird.png
Labels: documentation, priority.High

#10 Update NFR section of DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#18 Update README file
  README.md
  docs/images/Ui.png
Labels: documentation, priority.High

#15 Update Target User Details in DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#11 Update Command Summary in UG
  docs/UserGuide.md
Labels: documentation, priority.High

#23 Update user stories in DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#21 Update UC4 to UC6 of DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#22 Add add-seller feature to UG
  docs/UserGuide.md
Labels: documentation, priority.High

#24 Add some feature descriptions to UG
  docs/UserGuide.md
Labels: documentation

#26 update DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#30 #8. Fix naming
  docs/AboutUs.md
  docs/images/ruiyangzh.png
  docs/team/ruiyangzh.md
Labels: documentation, priority.High

#34 #33. Update Home Page for RTPM website
  docs/index.md
Labels: documentation

#27 Update User guide
  docs/UserGuide.md
Labels: documentation, priority.High

#44 [#7] Add Json adapted buyers and sellers
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/buyer/BuyHouseInfo.java
  src/main/java/seedu/address/model/person/buyer/Buyer.java
  src/main/java/seedu/address/model/person/seller/SellHouseInfo.java
  src/main/java/seedu/address/model/person/seller/Seller.java
  src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
  src/main/java/seedu/address/storage/JsonAdaptedSeller.java
Labels: priority.High, feature

#48 [#7] Added UniqueDisplayableList to genericize UniquePersonList
  src/main/java/seedu/address/model/person/UniqueDisplayableList.java
  src/main/java/seedu/address/model/util/Displayable.java
Labels: help wanted, priority.High

#47 [Partial #7] Added DisplayableListPanel to genericise PersonListPanel
  src/main/java/seedu/address/model/util/Displayable.java
  src/main/java/seedu/address/ui/DisplayableListPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: help wanted, priority.High

#51 [#50] Implement displayable
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/buyer/Buyer.java
  src/main/java/seedu/address/model/person/seller/Seller.java
  src/main/java/seedu/address/model/util/Displayable.java
Labels: enhancement, priority.High

#52 [#50] Add cards and abstractify PersonCard
  src/main/java/seedu/address/ui/BuyerCard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/SellerCard.java
Labels: enhancement, priority.High

#46 [Partial #7] Add deletion commands
  src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSellersCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteSellerCommandParser.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
Labels: help wanted, priority.High, feature

#64 Make 2 lists save as 2 files
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
Labels: enhancement

#70 [#61] Fix ui errors
  src/main/resources/view/BuyerListCard.fxml
  src/main/resources/view/DisplayableListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SellerListCard.fxml
Labels: fix

#119 [#107] Add priority
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java
  src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetBuyerPriorityCommandParser.java
  src/main/java/seedu/address/logic/parser/SetSellerPriorityCommandParser.java
  src/main/java/seedu/address/model/displayable/Person.java
  src/main/java/seedu/address/model/displayable/Priority.java
  src/main/java/seedu/address/model/displayable/buyer/Buyer.java
  src/main/java/seedu/address/model/displayable/seller/Seller.java
  src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSeller.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/BuyerListCard.fxml
  src/main/resources/view/SellerListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/SetBuyerPriorityCommandTest.java
  src/test/java/seedu/address/logic/commands/SetSellerPriorityCommandTest.java
  src/test/java/seedu/address/model/displayable/buyer/BuyerTest.java
  src/test/java/seedu/address/model/displayable/seller/SellerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSellerTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: feature

#122 Add Priority implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/SetBuyerPrioritySequenceDiagram.puml
Labels: documentation

#126 Refactor SellHouseInfo and BuyHouseInfo into info
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/displayable/HouseInfo.java
  src/main/java/seedu/address/model/displayable/Info.java
  src/main/java/seedu/address/model/displayable/buyer/BuyHouseInfo.java
  src/main/java/seedu/address/model/displayable/buyer/Buyer.java
  src/main/java/seedu/address/model/displayable/house/House.java
  src/main/java/seedu/address/model/displayable/seller/SellHouseInfo.java
  src/main/java/seedu/address/model/displayable/seller/Seller.java
  src/main/java/seedu/address/storage/JsonAdaptedBuyer.java
  src/main/java/seedu/address/storage/JsonAdaptedSeller.java
  src/main/java/seedu/address/ui/BuyerCard.java
  src/main/java/seedu/address/ui/HouseCard.java
  src/main/java/seedu/address/ui/SellerCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/displayable/HouseInfoTest.java
  src/test/java/seedu/address/model/displayable/buyer/BuyHouseInfoTest.java
  src/test/java/seedu/address/model/displayable/buyer/BuyerTest.java
  src/test/java/seedu/address/model/displayable/house/HouseTest.java
  src/test/java/seedu/address/model/displayable/seller/SellHouseInfoTest.java
  src/test/java/seedu/address/model/displayable/seller/SellerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBuyerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedSellerTest.java
  src/test/java/seedu/address/testutil/BuyerBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
  src/test/java/seedu/address/testutil/TypicalBuyers.java
  src/test/java/seedu/address/testutil/TypicalSellers.java
Labels: priority.Medium, fix

#131 Allow flexible filling
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/model/displayable/Address.java
  src/main/java/seedu/address/model/displayable/Email.java
  src/main/java/seedu/address/model/displayable/HouseInfo.java
  src/main/java/seedu/address/model/displayable/Phone.java
  src/test/java/seedu/address/logic/parser/AddBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddSellerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/testutil/BuyerBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/SellerBuilder.java
Labels: enhancement, priority.Medium

#138 [Fixes #134] Integrate CommandWarnings into Edit command parsers
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EditBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditSellerCommandParser.java
Labels: priority.High, fix

#139 [Closes #108] Create sort feature
  src/main/java/seedu/address/logic/commands/SortBuyerCommand.java
  src/main/java/seedu/address/logic/commands/SortSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/SortSellerCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/displayable/HouseInfo.java
Labels: type.Story, priority.High, feature

#140 Fix Sort commands to use CommandWarnings
  src/main/java/seedu/address/logic/commands/SortBuyerCommand.java
  src/main/java/seedu/address/logic/commands/SortSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/SortSellerCommandParser.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
Labels: priority.High, fix

#132 Update DG for implementation of CommandWarnings, minor fixes
  docs/DeveloperGuide.md
  docs/diagrams/isAppropriateNameSequenceDiagram.puml
  docs/index.md
Labels: documentation, priority.Medium
