Repository AY2324S1-CS2103T-F11-3/tp, pull requests merged in 2023-11, with the labels that each got.

#141 Add link to release in UG
  docs/UserGuide.md
Labels: documentation

#152 [#144] Improve command typability and case insensitivity
  src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java
  src/main/java/seedu/address/logic/commands/ListBuyersCommand.java
  src/main/java/seedu/address/logic/commands/ListSellersCommand.java
  src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: priority.Medium, fix

#153 [#151] Implement fuzzy name matching and warning
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/displayable/Displayable.java
  src/main/java/seedu/address/model/displayable/Name.java
  src/main/java/seedu/address/model/displayable/Person.java
  src/main/java/seedu/address/model/displayable/UniqueDisplayableList.java
  src/main/java/seedu/address/model/displayable/buyer/Buyer.java
  src/main/java/seedu/address/model/displayable/house/House.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
Labels: enhancement, priority.Medium

#159 Allow case-insensitive prefixes
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
Labels: priority.High, fix

#156 [Closes #133] Add warning for same name in buyer & seller list
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/displayable/Person.java
  src/main/java/seedu/address/model/displayable/UniqueDisplayableList.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
Labels: enhancement

#161 Align test cases to expected behavior
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
Labels: priority.Medium, fix

#160 Fix AddSeller not updating
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
Labels: priority.Medium, fix

#154 [#150] Change list, listb, and lists
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListBuyerCommand.java
  src/main/java/seedu/address/logic/commands/ListBuyersCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListSellerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/ListSellerCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ListBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/ListSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/ListSellersCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement

#130 [Closes #110] Create undo & redo feature
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteBuyerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteSellerCommand.java
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/AddBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteSellerCommandTest.java
  src/test/java/seedu/address/logic/commands/SetBuyerPriorityCommandTest.java
  src/test/java/seedu/address/logic/commands/SetSellerPriorityCommandTest.java
Labels: priority.Medium, feature

#164 Rectify edit command tests to work
  src/test/java/seedu/address/logic/commands/EditBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/EditSellerCommandTest.java
Labels: fix

#165 [Closes #147] Update UG for 1.3
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/EditBuyerCommand.java
  src/main/java/seedu/address/logic/commands/EditSellerCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/SortBuyerCommand.java
  src/main/java/seedu/address/logic/commands/SortSellerCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
Labels: documentation, priority.High

#166 Fix UG errors and omissions
  docs/UserGuide.md
Labels: priority.High, fix

#167 [Closes #145] Update GUI for buyer/seller lists
  src/main/resources/view/MainWindow.fxml
Labels: enhancement, priority.Medium

#168 Update UG for set priority commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/model/displayable/Priority.java
Labels: documentation, enhancement

#169 Add set priority in command summary
  docs/UserGuide.md
Labels: documentation

#170 Update Ui image
  docs/images/Ui.png
Labels: documentation, priority.High, fix

#200 Fix some PE-D bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: documentation

#201 Update documentation
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/isAppropriateNameSequenceDiagram.puml
  docs/team/ruiyangzh.md
Labels: documentation, priority.Medium

#205 Add default addressbook
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.Medium, fix

#203 Update UG for 1.4
  docs/UserGuide.md
  docs/images/Ui.png
  src/main/java/seedu/address/logic/parser/EditSellerCommandParser.java
Labels: documentation

#208 Fix prio bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
Labels: documentation, fix

#206 Logic testcases
  src/main/java/seedu/address/logic/commands/ListBuyerCommand.java
  src/main/java/seedu/address/logic/commands/ListSellerCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/CommandWarningsTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/WarningsTest.java
  src/test/java/seedu/address/logic/commands/ListBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/ListSellerCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ListSellerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/Assert.java
  src/test/java/seedu/address/testutil/FunctionWithWarnings.java
Labels: priority.Medium, fix

#219 Update DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#216 Update DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#218 Update UG, DG, PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ruiyangzh.md
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
Labels: documentation, priority.High

#223 Update UG for sort commands
  docs/UserGuide.md
Labels: documentation, priority.High

#217 Improve code quality for v1.4
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/commons/core/Version.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/commons/util/ToStringBuilder.java
  src/main/java/seedu/address/logic/CommandWarnings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddBuyerCommand.java
  src/main/java/seedu/address/logic/commands/AddSellerCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SortBuyerCommand.java
  src/main/java/seedu/address/logic/commands/SortSellerCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/AddBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSellerCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/displayable/Address.java
  src/main/java/seedu/address/model/displayable/Person.java
  src/main/java/seedu/address/model/displayable/Priority.java
  src/main/java/seedu/address/model/displayable/UniqueDisplayableList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/BuyerCard.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/DisplayableListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/SellerCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/CommandWarningsTest.java
  src/unused/HouseCard.java
  src/unused/Price.java
  src/unused/house/House.java
  src/unused/house/HouseTest.java
Labels: priority.Medium, codequality

#226 Format UG
  docs/UserGuide.md
Labels: documentation, priority.High

#228 Format UG draft 2
  docs/UserGuide.md
Labels: documentation, priority.High

#229 Update DG for sort and undo/redo commands
  docs/DeveloperGuide.md
  docs/diagrams/SortBuyerSequenceDiagram.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
Labels: documentation, priority.High

#235 Minor touch-ups to documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ruiyangzh.md
Labels: documentation, priority.High

#220 [Closes #179] Fix sort feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SortBuyerCommand.java
  src/main/java/seedu/address/logic/commands/SortSellerCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortBuyerCommandParser.java
  src/main/java/seedu/address/logic/parser/SortSellerCommandParser.java
  src/main/java/seedu/address/model/displayable/Priority.java
  src/main/java/seedu/address/model/displayable/SortOrder.java
  src/main/java/seedu/address/model/displayable/buyer/BuyerComparator.java
  src/main/java/seedu/address/model/displayable/seller/SellerComparator.java
  src/test/java/seedu/address/logic/commands/SortBuyerCommandTest.java
  src/test/java/seedu/address/logic/commands/SortSellerCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SortBuyerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortSellerCommandParserTest.java
  src/test/java/seedu/address/model/displayable/SortOrderTest.java
  src/test/java/seedu/address/model/displayable/buyer/BuyerComparatorTest.java
  src/test/java/seedu/address/model/displayable/seller/SellerComparatorTest.java
Labels: priority.High, fix

#225 Add more tests for priority
  src/main/java/seedu/address/model/displayable/Priority.java
  src/test/java/seedu/address/model/displayable/PriorityTest.java
Labels: priority.Low, addtests

#237 Add JUnit tests for undo & redo feature
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: priority.High, addtests

#239 Update manual testing and enhancements in DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#240 Format UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High

#238 Update PPP
  docs/team/iantsaii.md
  docs/team/johndoe.md
  docs/team/peasantbird.md
Labels: documentation, priority.High

#245 Minor javadoc edits
  src/main/java/seedu/address/logic/commands/SetBuyerPriorityCommand.java
  src/main/java/seedu/address/logic/commands/SetSellerPriorityCommand.java
  src/main/java/seedu/address/logic/parser/SetBuyerPriorityCommandParser.java
  src/main/java/seedu/address/logic/parser/SetSellerPriorityCommandParser.java
Labels: documentation

#246 Partial improvement of UG
  docs/UserGuide.md
Labels: documentation, help wanted, priority.High

#250 Update UG for sort, undo/redo, help and exit
  docs/UserGuide.md
Labels: documentation, priority.High

#247 UG: delete to priority section
  docs/UserGuide.md
Labels: documentation, priority.High

#248 Update ug filter to slist
  docs/UserGuide.md
Labels: documentation, priority.High

#249 Edit content of UG
  docs/UserGuide.md
Labels: documentation, priority.High

#252 Edit expected outputs format
  docs/UserGuide.md
Labels: documentation, priority.High

#251 Rework output message examples
  docs/UserGuide.md
Labels: documentation, priority.High

#253 Format UG
  docs/UserGuide.md
  docs/images/startUi.PNG
Labels: documentation, priority.High

#254 Reformat features section
  docs/UserGuide.md
Labels: documentation, priority.High
